[package]
name = "telemarketing-flow"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = { version = "0.9", features = ["v4_18"] }
gdk4 = { version = "0.9", features = ["v4_18"] }
webkit6 = "0.4.0"
glib = "0.20"